# Generated by Django 6.1.1 on 2026-09-06 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('initials', models.CharField(blank=True, max_length=8)),
                ('mrn', models.CharField(help_text='Medical Record Number (e.g. ST-2048)', max_length=50, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Emergency (Immediate)'), (2, 'High Priority (Needs Review)'), (3, 'Urgent'), (4, 'Non-urgent')], default=3)),
                ('primary_complaint', models.CharField(max_length=255)),
                ('symptom_onset', models.CharField(default='About 30 minutes ago', max_length=150)),
                ('severe_breathing_difficulty', models.BooleanField(default=False)),
                ('chest_pain_or_pressure', models.BooleanField(default=False)),
                ('slurred_speech_or_weakness', models.BooleanField(default=False)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ai_suggested_priority', models.IntegerField(blank=True, choices=[(1, 'Emergency (Immediate)'), (2, 'High Priority (Needs Review)'), (3, 'Urgent'), (4, 'Non-urgent')], null=True)),
                ('ai_rationale', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='triage.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30)),
                ('priority', models.IntegerField(choices=[(1, 'Emergency (Immediate)'), (2, 'High Priority (Needs Review)'), (3, 'Urgent'), (4, 'Non-urgent')], default=3)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Triage in progress', 'Triage in progress'), ('Triage complete', 'Triage complete'), ('In consultation', 'In consultation'), ('Completed', 'Completed')], default='Waiting', max_length=30)),
                ('assigned_room', models.CharField(default='A-01', max_length=50)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=15)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='triage.patient')),
                ('triage_assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='triage.triageassessment')),
            ],
            options={
                'ordering': ['priority', 'arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='Oxygen saturation %', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate bpm', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure mmHg', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure mmHg', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature Celsius', max_digits=4, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='triage.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
