# Generated by Django 6.1.1 on 2026-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_patient_created_at_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, help_text='Medical Record Number (e.g. ST-2048)', max_length=50, unique=True),
        ),
    ]
