# Generated by Django 6.1.1 on 2026-09-07 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('triage', '0003_alter_patient_mrn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(blank=True, help_text='Visit Encounter ID (e.g. VIS-2048)', max_length=50, unique=True)),
                ('chief_complaint', models.CharField(default='Pending triage assessment', max_length=255)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Waiting', 'Waiting'), ('Triage in progress', 'Triage in progress'), ('Triage complete', 'Triage complete'), ('In consultation', 'In consultation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=30)),
                ('priority', models.IntegerField(choices=[(1, 'Emergency (Immediate)'), (2, 'High Priority (Needs Review)'), (3, 'Urgent'), (4, 'Non-urgent')], default=4)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='triage.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='queueticket',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='triage.visit'),
        ),
    ]
