# Generated by Django 6.1.1 on 2026-09-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_visit_queueticket_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageassessment',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to='triage.visit'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='triage.visit'),
        ),
    ]
