# Generated by Django 5.1.15 on 2026-09-09 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_triageassessment_visit_vitalsign_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for patient self-service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Lab Result', 'Lab Result'), ('Imaging', 'Imaging'), ('Prescription', 'Prescription'), ('Discharge Summary', 'Discharge Summary'), ('Vitals Summary', 'Vitals Summary'), ('Clinical Note', 'Clinical Note'), ('Other', 'Other')], default='Clinical Note', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='health_reports/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Clinical notes by nurse/doctor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='triage.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_reports', to='triage.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
