'use client'

import { useState } from 'react'
import {
  Activity, AlertCircle, Bell, BrainCircuit, CalendarDays, CheckCircle2, ChevronDown,
  Clock3, FileText, HeartPulse, History, LayoutDashboard, ListFilter, Menu, MessageSquare,
  MoreHorizontal, Search, Settings, ShieldCheck, Stethoscope, UserRound, Users, X,
} from 'lucide-react'

type Priority = 1 | 2 | 3 | 4
type Role = 'Doctor' | 'Nurse' | 'Admin' | 'Patient'

const patients = [
  { name: 'John Doe', initials: 'JD', age: 64, complaint: 'Severe breathing difficulty', priority: 1 as Priority, wait: '4 min', vital: 'SpO₂ 86%', status: 'Waiting', room: 'A-04' },
  { name: 'Maria Santos', initials: 'MS', age: 41, complaint: 'Sudden weakness and slurred speech', priority: 2 as Priority, wait: '18 min', vital: 'BP 178/104', status: 'Waiting', room: 'A-02' },
  { name: 'Samuel Lee', initials: 'SL', age: 29, complaint: 'Deep laceration to left hand', priority: 2 as Priority, wait: '26 min', vital: 'HR 112 bpm', status: 'Waiting', room: 'A-01' },
  { name: 'Eleanor Wright', initials: 'EW', age: 72, complaint: 'Fever and persistent cough', priority: 3 as Priority, wait: '34 min', vital: 'Temp 38.4°C', status: 'Waiting', room: 'B-07' },
  { name: 'David Kim', initials: 'DK', age: 36, complaint: 'Abdominal pain, 2 hours', priority: 3 as Priority, wait: '42 min', vital: 'Normal', status: 'Triage complete', room: 'B-03' },
  { name: 'Aisha Patel', initials: 'AP', age: 25, complaint: 'Prescription renewal', priority: 4 as Priority, wait: '51 min', vital: 'Normal', status: 'Waiting', room: 'C-02' },
]

const priorityMeta = {
  1: { label: 'Emergency', code: 'LEVEL 1', color: 'red', tint: 'red-tint' },
  2: { label: 'High priority', code: 'LEVEL 2', color: 'amber', tint: 'amber-tint' },
  3: { label: 'Urgent', code: 'LEVEL 3', color: 'gold', tint: 'gold-tint' },
  4: { label: 'Non-urgent', code: 'LEVEL 4', color: 'teal', tint: 'teal-tint' },
}

function PriorityBadge({ level, compact = false }: { level: Priority; compact?: boolean }) {
  const p = priorityMeta[level]
  return <span className={`priority-badge ${p.color}`}><span className="priority-dot" />{compact ? p.code : `${p.code} — ${p.label}`}</span>
}

function StatusBadge({ children }: { children: string }) {
  return <span className={`status-badge ${children === 'Waiting' ? 'waiting' : children === 'In consultation' ? 'consulting' : ''}`}><span className="status-dot" />{children}</span>
}

function Sidebar({ role, setRole }: { role: Role; setRole: (role: Role) => void }) {
  const links = role === 'Doctor' ? [['Command center', LayoutDashboard], ['Queue', ListFilter], ['Patients', Users], ['History', History]] : role === 'Nurse' ? [['Overview', LayoutDashboard], ['Patients', Users], ['Triage', HeartPulse], ['Queue', ListFilter], ['History', History]] : role === 'Admin' ? [['Operations', LayoutDashboard], ['Patients', Users], ['Queue', ListFilter], ['Staff', UserRound], ['Settings', Settings]] : [['Home', LayoutDashboard], ['My visit', FileText], ['Queue', Clock3], ['Profile', UserRound]]
  return <aside className="sidebar">
    <div className="brand"><span className="brand-mark"><HeartPulse size={19} /></span><span>Smart<span>Triage</span></span></div>
    <div className="facility"><span className="facility-dot" />Northside Medical Center<ChevronDown size={14} /></div>
    <nav className="side-nav">{links.map(([label, Icon]: any, i) => <button key={label as string} className={`nav-item ${i === 0 ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{label === 'Queue' && <span className="nav-count">14</span>}</button>)}</nav>
    <div className="side-bottom"><button className="nav-item"><ShieldCheck size={18} /><span>Help & safety</span></button><div className="user-mini"><div className="avatar">{role === 'Doctor' ? 'AR' : role === 'Nurse' ? 'JL' : 'SM'}</div><div><strong>{role === 'Doctor' ? 'Dr. Alex Rivera' : role === 'Nurse' ? 'Jordan Lee' : role === 'Admin' ? 'Sam Morgan' : 'Jamie Smith'}</strong><small>{role}</small></div><MoreHorizontal size={17} /></div></div>
  </aside>
}

function Topbar({ role, onMenu }: { role: Role; onMenu: () => void }) { return <header className="topbar"><button className="mobile-menu" onClick={onMenu}><Menu size={20} /></button><div className="top-search"><Search size={17} /><input placeholder="Search patients by name or ID" /><kbd>⌘ K</kbd></div><div className="top-actions"><span className="sync"><span />Live queue</span><button className="icon-button" aria-label="Notifications"><Bell size={19} /><i /></button><div className="top-avatar">{role === 'Doctor' ? 'AR' : role === 'Nurse' ? 'JL' : 'SM'}</div></div></header> }

function PatientRow({ patient, onOpen }: { patient: typeof patients[0]; onOpen: () => void }) { return <div className={`patient-row priority-${patient.priority}`}><div className="patient-person"><div className="avatar patient-avatar">{patient.initials}</div><div><strong>{patient.name}</strong><span>{patient.age} years · {patient.room}</span></div></div><div className="complaint">{patient.complaint}</div><div><PriorityBadge level={patient.priority} compact /></div><div className="vital-inline"><Activity size={14} />{patient.vital}</div><div className="wait"><Clock3 size={14} />{patient.wait}</div><StatusBadge>{patient.status}</StatusBadge><button className="row-action" onClick={onOpen}>Open <span>→</span></button></div> }

function AttentionCard({ patient, onOpen }: { patient: typeof patients[0]; onOpen: () => void }) { return <article className={`attention-card level-${patient.priority}`}><div className="attention-top"><PriorityBadge level={patient.priority} /><span className="new-label">{patient.priority === 1 ? 'Immediate attention' : 'Needs review'}</span></div><div className="attention-body"><div className="avatar patient-avatar large">{patient.initials}</div><div><h3>{patient.name}</h3><p>{patient.age} years · {patient.complaint}</p></div></div><div className="attention-meta"><span><Activity size={15} /> <strong>{patient.vital}</strong></span><span><Clock3 size={15} /> Waiting {patient.wait}</span><StatusBadge>{patient.status}</StatusBadge></div><button className="primary-action" onClick={onOpen}>Open patient <span>→</span></button></article> }

function Assistant() { return <section className="assistant-panel"><div className="assistant-heading"><div className="assistant-icon"><BrainCircuit size={18} /></div><div><h2>Clinical assistant</h2><p>AI-assisted information to support clinical review.</p></div><button className="icon-button"><MoreHorizontal size={18} /></button></div><div className="ai-disclaimer"><ShieldCheck size={14} /><span>AI-generated <b>•</b> Clinical review required</span></div><div className="summary-block"><div className="summary-label">Patient summary</div><p>John presents with severe breathing difficulty. Recorded oxygen saturation is below the expected range and requires prompt clinical assessment.</p></div><div className="summary-block"><div className="summary-label">Why this patient is prioritized</div><p>Priority is based on the reported symptom and recorded vital signs.</p></div><div className="ai-actions"><button><MessageSquare size={15} />Ask about this patient</button><button><FileText size={15} />Summarize history</button></div><small className="ai-time">Generated just now · Structured visit data</small></section> }

function DoctorView({ onOpen }: { onOpen: () => void }) { return <><div className="page-heading"><div><div className="eyebrow">Thursday, September 6, 2026 · 10:44 AM</div><h1>Who needs my attention?</h1><p className="page-subtitle">Good morning, Dr. Rivera. Here is the current clinical priority.</p></div><button className="availability"><span />Available <ChevronDown size={14} /></button></div><div className="alert-strip"><AlertCircle size={19} /><div><strong>1 new emergency patient</strong><span>Arrived 2 minutes ago and is waiting for immediate attention.</span></div><button onClick={onOpen}>Review now →</button><X size={17} /></div><section className="section"><div className="section-heading"><div><h2>Needs attention now</h2><p>Start with patients requiring the most urgent assessment.</p></div><button className="text-button">View all 3 <span>→</span></button></div><div className="attention-grid"><AttentionCard patient={patients[0]} onOpen={onOpen} /><AttentionCard patient={patients[1]} onOpen={onOpen} /></div></section><section className="section queue-section"><div className="section-heading"><div><h2>Waiting for assessment</h2><p>Sorted by urgency, then waiting time.</p></div><div className="heading-actions"><button className="filter-button"><ListFilter size={16} /> Filter</button><button className="text-button">Open queue →</button></div></div><div className="queue-table"><div className="queue-header"><span>Patient</span><span>Reason for visit</span><span>Priority</span><span>Vitals</span><span>Wait time</span><span>Status</span><span /></div>{patients.slice(2).map(p => <PatientRow key={p.name} patient={p} onOpen={onOpen} />)}</div></section></> }

function NurseView({ onOpen }: { onOpen: () => void }) { return <><div className="page-heading"><div><div className="eyebrow">Thursday, September 6, 2026</div><h1>Good morning, Jordan</h1><p className="page-subtitle">Here is what needs your attention first.</p></div><button className="primary-action small" onClick={onOpen}>Start next triage <span>→</span></button></div><div className="workflow-cards"><div className="workflow-card urgent"><AlertCircle size={18} /><div><strong>3 patients</strong><span>Need triage</span></div><b>→</b></div><div className="workflow-card"><HeartPulse size={18} /><div><strong>2 patients</strong><span>Triage in progress</span></div><b>→</b></div><div className="workflow-card"><Clock3 size={18} /><div><strong>8 patients</strong><span>Waiting for care</span></div><b>→</b></div></div><section className="section"><div className="section-heading"><div><h2>Patients needing triage</h2><p>New arrivals are ready to be assessed.</p></div><button className="filter-button"><Search size={16} /> Search</button></div><div className="nurse-list">{patients.slice(0, 4).map(p => <div className="nurse-patient" key={p.name}><div className="avatar patient-avatar">{p.initials}</div><div className="nurse-name"><strong>{p.name}</strong><span>{p.age} years · Arrived {p.wait} ago</span></div><div className="nurse-complaint">{p.complaint}</div><PriorityBadge level={p.priority} compact /><button className="row-action" onClick={onOpen}>Begin triage <span>→</span></button></div>)}</div></section><section className="section safety-note"><ShieldCheck size={19} /><div><strong>Clinical workflow reminder</strong><p>SmartTriage supports your assessment. Always use clinical judgment and follow facility protocols.</p></div></section></> }

function PatientView() { return <><div className="patient-welcome"><div><div className="eyebrow">Northside Medical Center</div><h1>Hello, Jamie</h1><p className="page-subtitle">Here is the latest update on your visit.</p></div><div className="patient-top-avatar">JS</div></div><section className="patient-status-card"><div className="status-card-top"><div><span className="live-label"><span />Current status</span><h2>Your visit is in progress</h2></div><StatusBadge>Waiting</StatusBadge></div><div className="queue-position"><div><span>Your queue position</span><strong>4</strong><small>of 12 patients waiting</small></div><div className="position-divider" /><div><span>Estimated wait</span><strong>~18 min</strong><small>Updated just now</small></div></div><div className="patient-instruction"><InfoIcon /><span>Please remain available in the waiting area. We will call your name when it is time for your assessment.</span></div></section><div className="patient-columns"><section className="simple-card"><div className="card-title"><CalendarDays size={18} /><h2>Today&apos;s visit</h2></div><div className="visit-line"><span>Visit ID</span><strong>ST-2048</strong></div><div className="visit-line"><span>Status</span><StatusBadge>Waiting</StatusBadge></div><div className="visit-line"><span>Next step</span><strong>Nurse assessment</strong></div><button className="secondary-action">View visit details <span>→</span></button></section><section className="simple-card"><div className="card-title"><ShieldCheck size={18} /><h2>Need help?</h2></div><p className="help-copy">If your symptoms change or become more severe, please tell a member of staff right away.</p><button className="secondary-action">How triage works <span>→</span></button></section></div></> }
function InfoIcon() { return <span className="info-icon">i</span> }

function AdminView() { return <><div className="page-heading"><div><div className="eyebrow">Thursday, September 6, 2026 · 10:44 AM</div><h1>Operations</h1><p className="page-subtitle">A live view of patient flow at Northside Medical Center.</p></div><button className="filter-button"><CalendarDays size={16} /> Today <ChevronDown size={14} /></button></div><div className="operations-grid"><div><span>Arrivals</span><strong>24</strong><small>+4 from yesterday</small></div><div><span>Waiting</span><strong>12</strong><small>8 under 30 min</small></div><div><span>In triage</span><strong>3</strong><small>2 nurses active</small></div><div><span>With doctor</span><strong>5</strong><small>3 rooms occupied</small></div><div><span>Completed</span><strong>18</strong><small>Today</small></div></div><div className="admin-columns"><section className="section admin-queue"><div className="section-heading"><div><h2>Queue overview</h2><p>Patient flow by current status.</p></div><button className="text-button">View queue →</button></div>{[['Emergency', '1', 'red'], ['High priority', '2', 'amber'], ['Urgent', '5', 'gold'], ['Non-urgent', '4', 'teal']].map(([label, count, color]) => <div className="flow-row" key={label}><span className={`flow-dot ${color}`} /><strong>{label}</strong><span className="flow-count">{count} patients</span><div className="flow-bar"><i className={color} style={{ width: `${Number(count) * 15 + 10}%` }} /></div><span className="flow-arrow">→</span></div>)}</section><section className="section activity"><div className="section-heading"><div><h2>Recent activity</h2><p>Today&apos;s latest updates.</p></div></div>{[['10:42 AM', 'Triage completed', 'David Kim'], ['10:39 AM', 'Vitals recorded', 'Eleanor Wright'], ['10:35 AM', 'Patient registered', 'Aisha Patel'], ['10:31 AM', 'Consultation started', 'Maria Santos']].map(a => <div className="activity-row" key={a[0]}><span>{a[0]}</span><div><strong>{a[1]}</strong><small>{a[2]}</small></div></div>)}</section></div></> }

function DetailView({ onBack }: { onBack: () => void }) { const p = patients[0]; return <><button className="back-link" onClick={onBack}>← Back to command center</button><div className="detail-header"><div className="patient-person"><div className="avatar patient-avatar large">{p.initials}</div><div><div className="eyebrow">Patient record · ST-2048</div><h1>{p.name}</h1><p>{p.age} years · Male · Registered today at 10:35 AM</p></div></div><div className="detail-actions"><PriorityBadge level={1} /><button className="primary-action">Start consultation <span>→</span></button></div></div><div className="detail-grid"><main><section className="clinical-card critical-card"><div className="card-title"><AlertCircle size={18} /><h2>Immediate concern</h2></div><h3>{p.complaint}</h3><p>Patient is waiting for prompt clinical assessment.</p><div className="detail-vitals"><div><span>SpO₂</span><strong className="critical-text">86%</strong><small>Needs attention</small></div><div><span>Heart rate</span><strong>112 <em>bpm</em></strong><small>Elevated</small></div><div><span>Respiratory rate</span><strong>28 <em>/min</em></strong><small>Elevated</small></div></div></section><section className="clinical-card"><div className="card-title"><HeartPulse size={18} /><h2>Triage responses</h2><button className="card-link">View all</button></div><div className="answer-row"><span>Severe breathing difficulty?</span><strong>Yes</strong></div><div className="answer-row"><span>Chest pain or pressure?</span><strong>No</strong></div><div className="answer-row"><span>Symptoms started</span><strong>About 30 minutes ago</strong></div></section><section className="clinical-card"><div className="card-title"><History size={18} /><h2>Patient history</h2></div><div className="empty-record"><FileText size={19} /><div><strong>No previous records available</strong><p>No previous visits or consultations are available for this patient.</p></div></div></section></main><aside><Assistant /><section className="clinical-card timeline"><div className="card-title"><Clock3 size={18} /><h2>Visit timeline</h2></div>{[['10:42 AM', 'Triage completed'], ['10:39 AM', 'Vitals recorded'], ['10:35 AM', 'Patient registered']].map(x => <div className="timeline-row" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</section></aside></div></> }

export default function Page() { const [role, setRole] = useState<Role>('Doctor'); const [detail, setDetail] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const view = role === 'Doctor' ? <DoctorView onOpen={() => setDetail(true)} /> : role === 'Nurse' ? <NurseView onOpen={() => setDetail(true)} /> : role === 'Patient' ? <PatientView /> : <AdminView />; return <div className="app-shell"><div className={mobileOpen ? 'sidebar-wrap open' : 'sidebar-wrap'}><Sidebar role={role} setRole={setRole} /></div><div className="main-shell"><Topbar role={role} onMenu={() => setMobileOpen(!mobileOpen)} /><div className="role-switcher"><span>Demo view</span>{(['Doctor', 'Nurse', 'Admin', 'Patient'] as Role[]).map(r => <button className={role === r ? 'selected' : ''} key={r} onClick={() => { setRole(r); setDetail(false) }}>{r}</button>)}</div><main className="content">{detail && role !== 'Patient' ? <DetailView onBack={() => setDetail(false)} /> : view}</main></div></div> }
