# Generated by Django 6.1.1 on 2026-09-06 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('clinical_findings', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment_plan', models.TextField(blank=True)),
                ('disposition', models.CharField(choices=[('Discharged', 'Discharged home'), ('Admitted', 'Admitted to inpatient ward'), ('Observation', 'Extended clinical observation'), ('Transferred', 'Transferred to tertiary facility')], default='Discharged', max_length=50)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='triage.patient')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
